version: "3"

services:
  nginx:
    container_name: nginx
    ports:
      - "80:80"
    build:
      context: ./nginx/
    networks:
      - nginx-net
    depends_on:
      - node-app

  node-app:
    container_name: node-app
    build:
      context: ./backend/
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PWD=/app
    networks:
      - api-net
      - nginx-net
    command: node ./app.js

networks:
  api-net: {}
  nginx-net: {}