# deploy file for mqtt-blackbox-exporter
# author: amirhnajafiz
# year: 2022
apiVersion: v1
kind: Application
metadata:
  name: stan-gee
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amirhnajafiz/Stan-Gee.git
    targetRevision: HEAD
  destination:
    server: # Where to go?
    namespace: argocd
stringData:
  name: stan-gee
  url: https://github.com/amirhnajafiz/Stan-Gee/deployments/stan-gee
  type: helm