apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include .Release.Name }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "stan-gee.labels" . | indent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | default "{}" | indent 4 }}